databases:
  - name: contact-manager-db
    plan: free
    databaseName: contact_manager

services:
  # Backend Service
  - type: web
    name: contact-manager-api
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn wsgi:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: contact-manager-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ALLOW_ORIGINS
        value: https://contact-manager-frontend-h56q.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend Service
  - type: web
    name: contact-manager-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://contact-manager-api-bc37.onrender.com/api
